<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="{$smarty.const.CHARSET}/"/>
	<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8"/>
	<title>{$smarty.const.APPLICATION_NAME}</title>

	<!-- Styles -->
	<link rel="stylesheet" type="text/css" media="screen"
		  href="{$smarty.const.PUBLICHTML_URL}css/application.css"/>
	<link rel="stylesheet" type="text/css" media="screen"
		  href="{$smarty.const.PUBLICHTML_URL}lib/bootstrap/css/bootstrap.css"/>
	<link rel="stylesheet" type="text/css" media="screen"
		  href="{$smarty.const.PUBLICHTML_URL}lib/bootstrap/css/bootstrap_edited.css"/>

	<!-- Scripts -->
	<script src="{$smarty.const.PUBLICHTML_URL}lib/jquery/jquery-1.7.2.js"></script>
	<script src="{$smarty.const.PUBLICHTML_URL}js/application.js"></script>
	<script src="{$smarty.const.PUBLICHTML_URL}js/Grid.class.js"></script>

</head>
<body>

{include file="menuTop.phtml"}

<div class="container">
	<div class="content">