<div class="span3">
	<div class="well">
		<ul class="nav nav-list">
			<li class="nav-header">Person</li>
			<li class="active">
				<a href="?optTela=list" class="list">
					<i class="icon-list icon-white"></i>
					Person List
				</a>
			</li>
			<li>
				<a href="?optTela=create" class="create">
					<i class="icon-plus"></i>
					Create Person
				</a>
			</li>
		</ul>
	</div>
</div>